---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
otel_endpoint: ""
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

triedb_config:
   drive: /dev/sda # Update with the drive you ae using
   path: /dev/triedb
   partition_name: triedb
   partition_number: 1

monad:
  source_url: https://pkg.category.xyz
  consensus:
    ports:
      p2p_port: 8000
      metrics_port: 8889
  execution:
  rpc:
