---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
pushgateway_dns: pushgateway.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

triedb_config:
  drive: /dev/nvme0n1 # Update with the drive you are using
  path: /dev/triedb-{{ type }}
  partition_name: triedb-{{ type }}
  partition_number: 1

triedb_loop_config:
  image_file: "/monad-triedb.img"
  image_size: "1T"

monad:
  source_url: https://pkg.category.xyz
  validator:
    consensus:
      ports:
        p2p_port: 8000
    rpc:
      ports:
        rpc_port: 8080
  fullnode:
    consensus:
      ports:
        p2p_port: 8000
    rpc:
      ports:
        rpc_port: 8090

otel:
  service_identifier_suffix: otel
  source_url: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download
  file_extension: tar.gz
  ports:
    grpc_port: 4317
    http_port: 4318
    prometheus_metrics_exporter_port: 8889
    metrics_port: 8888
