---
# maintains versions and can overwrite all.yml
monad:
  chain_id: monad_mainnet
  forkpoint_url: "https://bucket.monadinfra.com/forkpoint/mainnet"
  snapshot_url: ""
  validator_config_url: "https://bucket.monadinfra.com/validators/mainnet/validators.toml"
  fullnode:
    version: 0.12.0
    otel_endpoint: "http://0.0.0.0:4317"

triedb_config:
  path: /dev/triedb
  partition_name: triedb
