---
# maintains versions and can overwrite all.yml
monad:
  chain_id: monad_testnet
  forkpoint_url: "https://bucket.monadinfra.com/forkpoint/testnet"
  snapshot_url: "https://d1xd6bwr0bhisu.cloudfront.net"
  validator_config_url: "https://bucket.monadinfra.com/validators/testnet/validators.toml"
  validator:
    version: 0.11.3-tn1
    otel_endpoint: "http://0.0.0.0:4317"
  fullnode:
    version: 0.11.3-tn1
    otel_endpoint: "http://0.0.0.0:4317"
    consensus:
      ports:
        p2p_port: 8001

triedb_loop_config:
  image_file: "/opt/monad-triedb.img"
  image_size: "1T"
