---
# maintains versions and can overwrite all.yml
monad:
  consensus:
    version: 0.1.0-testnet-2-genesis
    forkpoint_url: ""
  execution:
    version: 0.1.0-testnet-2-genesis
  rpc:
    version: 0.1.0-testnet-2-genesis
