---
# maintains versions and can overwrite all.yml
monad:
  chain_id: monad_testnet2
  forkpoint_url: "https://bucket.monadinfra.com/forkpoint/testnet-2"
  snapshot_url: "https://d1xd6bwr0bhisu.cloudfront.net"
  validator_config_url: "https://bucket.monadinfra.com/validators/testnet-2/validators.toml"
  validator:
    version: 0.11.1-hotfix-execution
    otel_endpoint: "http://0.0.0.0:4317"
