$ANSIBLE_VAULT;1.1;AES256
64613462386430383865633063623636393161323036643231366634353632653866383331326161
3163303533353031663338326165383237303638353933350a356439623234636139613561366664
33656133386430613630306533303538316339633164323862633532393935396638356630623564
3238326532663030640a636432376437613736633933326139316433306434653131383334373861
61306539306431313534653432326234383932663437303564326532363539303733336361326662
39336138656332363039643437613166386237636139356361366366626366373430663733613232
32393563366431653434653630343938343132333237613536343566376336363964633966616166
62626334383930353837633432393338643732326632633764373661633634396666373838396430
37373934656331393238653739393337373564653737383635363731383531633932643164646634
31616338353535366630343439316136393966343631326439633133343539656461633864636265
63666330353435616366323237383730363035663336643863393332323362383466636130613538
35356536383236333339353665336665663663623238663239613661353937306637653561363031
33353239363432303735633435646336643638333037626566616634613937623766636165316634
39396435373463346237616666643961636437393565616534333431633633383063643536356137
34303536356431626161373732306166313965663763313339633166373562643938633134333533
35306233633332353937353331363136636432333330346633366232323034376265326633626632
38376432646634376661306439666534303733343735346536333530396566323531363836316561
62366462376330336663343662363666373133303433663231656534633565646533383062643938
64313335636533376434623039346263383661663430643234353835393636666663323035616164
63303935666235363363
