$ANSIBLE_VAULT;1.1;AES256
33303336366466343233623561326133666637616363633933623031653633643638626166613835
3864656231663364623836343034383934316135386631620a303331656137633930333165366231
61613065366262623565656161613332356466303561653637663335613034366230336466363536
3663343465383930310a303537396633666638356465616661663863346233393235626263623634
35343961326261616261613064643062376433633835626264306239313438633236623565323763
36396331376666373964663332363663386432623835623837316539386365613865316331623930
33343833366632393565643761613266376330396534383635373833656236653662363639643430
36383862336630386131336532306434623434646161376336353462633761643330346366373330
31396361633264313464383831646132643535393636366365343864343862333861396531373763
61373061656135303231646135663434326436663934623765633565383261663131366336373062
35653462323335666331663964653961643430623237653766353633626462386134626134616539
37623930656539396661636636363862643039316531363536626231626361356135373761373536
65386466653966383633633435666561333030613764316432353762633835313431363564663237
39613466363639313038363239363765363866633938623236383031643161326263626539323036
61613664656239643366373735643733363938373164613761356333353165386531383139653063
38613634623435313932
