[[validator_sets]]
epoch = 1

[[validator_sets.validators]]
node_id = "0x0252d15934d2cf43004048f8860b79354e39af2c55e62d52814c99fe48431f60a0"
stake = 1
cert_pubkey = "0x885ee1b19f3246cb2ada459d9aa4191d8561ab4b13d722a641f64949c5474208e40938f294333065b64129cd2bb5b015"

[[validator_sets.validators]]
node_id = "0x02a119eab665887783e605b1862e587a404548ae712f13607e2335f38ce409b500"
stake = 1
cert_pubkey = "0xa23e256bc4265bc4e0080493355991191b3e05c1f7972233dac9956cc708aa4d8a6c7b2eb25d52224ff305354bd5e8d7"

[[validator_sets.validators]]
node_id = "0x038922d0d2bc9f80823b27ce6520357534ad82764cfc8115668344e3fc9c1ec2c5"
stake = 1
cert_pubkey = "0xb8a540a4f28f9247e6a3589229487f443b5c8bb4ac918a777bd518853ebc405057a17ebf4af5724a0004df89f88d14d9"

[[validator_sets.validators]]
node_id = "0x02af89250541f621018dd022a8c3440327879115bd2e7d2d175f565c62d43b572f"
stake = 1
cert_pubkey = "0xb98cd2bdd62dee1b3bc3ce8fdaa1ac12c837411b4600edeebf42b87e1a1c80df6791804aaa0a5ee612f61e51ad315033"

[[validator_sets.validators]]
node_id = "0x030658fba49d3686fae3d8e81700e957a65f0ecd41f161d4847385d9a889e813c2"
stake = 1
cert_pubkey = "0xb4b57db2389dc325dd4238e8d80a92b5085c4b9b13eba372b66a977c457be96cde0e9839e23be61dd9718b1ba8d12f46"

[[validator_sets.validators]]
node_id = "0x02388f31dc7432ffc8e0fd33b0c9f3ed98aeb20978e5428955bb6152262bee2297"
stake = 1
cert_pubkey = "0x93042b1d6bb15100c4b0542f43ec79176e39a6a5a792254101a831f1a8f844b0d8aadaff762ee232d2f538eb1879bb23"

[[validator_sets.validators]]
node_id = "0x0205eebb2723764d375829cd55a4a9c2df95de1faf1067cc22cf49f1e42d09dbbd"
stake = 1
cert_pubkey = "0x95fce966e256ea785d33df7dc30d936c4f75aef10f87615705d31167a7e1fb66cc2226144b971d736ce351066a20e8ad"

[[validator_sets]]
epoch = 32

[[validator_sets.validators]]
node_id = "0x038922d0d2bc9f80823b27ce6520357534ad82764cfc8115668344e3fc9c1ec2c5"
stake = 20
cert_pubkey = "0xb8a540a4f28f9247e6a3589229487f443b5c8bb4ac918a777bd518853ebc405057a17ebf4af5724a0004df89f88d14d9"

[[validator_sets.validators]]
node_id = "0x030658fba49d3686fae3d8e81700e957a65f0ecd41f161d4847385d9a889e813c2"
stake = 20
cert_pubkey = "0xb4b57db2389dc325dd4238e8d80a92b5085c4b9b13eba372b66a977c457be96cde0e9839e23be61dd9718b1ba8d12f46"

[[validator_sets.validators]]
node_id = "0x02fbb9abb43cff6f29a6ca40182e526847ca132d42abab6d1af517c956d19f7c68"
stake = 1
cert_pubkey = "0x947f9e502343afda440ac057a4a7c3789ca740ca109b84c3463e9031a95e0fc1e878487c44ce3d1d4168b21bcd778da9"

[[validator_sets.validators]]
node_id = "0x031c8bc9614e6d2d9c3642a6cfb2c6edbbcee927db4eec4f21c104f84ee886ece0"
stake = 1
cert_pubkey = "0x8e2293ee11161b537de05c7f2f0348e7ddabcbea5a5ffc1c11e5e0432edc0e5a499929173e3f59006ae99a6845405d7d"

[[validator_sets.validators]]
node_id = "0x03f032be493752229481ab235b40d0351e384aeb170d93898f7713b7121460a045"
stake = 1
cert_pubkey = "0x915b8282adc0acd6dfb27203670dbfbcf12579e228d8891b46bc1fba673f6b712ef6b865737d89f99fcc1c44b728e7dd"

[[validator_sets.validators]]
node_id = "0x0265c19d462f24f7ece64ab180b6c7b893b8a8bc4184df8b7d539093e3d5daffee"
stake = 1
cert_pubkey = "0x8d5d5d7477ede7a6e0758379e94798f4db69ee76301749a2e4e39bed7242032c82079ac1204eea80a1f520eaa749ee0d"

[[validator_sets.validators]]
node_id = "0x0316e0861acf92dc4c0e357f73fe07263a87b65513a4b73750ab9194f9a39a6a54"
stake = 1
cert_pubkey = "0xa5861cf9bf42aee127f027efdcd21b5f68b55a28329949baaf057d2810a6d4f977ad58f588833cf3266b192c7417c908"

[[validator_sets]]
epoch = 42

[[validator_sets.validators]]
node_id = "0x038922d0d2bc9f80823b27ce6520357534ad82764cfc8115668344e3fc9c1ec2c5"
stake = 20
cert_pubkey = "0xb8a540a4f28f9247e6a3589229487f443b5c8bb4ac918a777bd518853ebc405057a17ebf4af5724a0004df89f88d14d9"

[[validator_sets.validators]]
node_id = "0x030658fba49d3686fae3d8e81700e957a65f0ecd41f161d4847385d9a889e813c2"
stake = 20
cert_pubkey = "0xb4b57db2389dc325dd4238e8d80a92b5085c4b9b13eba372b66a977c457be96cde0e9839e23be61dd9718b1ba8d12f46"

[[validator_sets.validators]]
node_id = "0x02fbb9abb43cff6f29a6ca40182e526847ca132d42abab6d1af517c956d19f7c68"
stake = 20
cert_pubkey = "0x947f9e502343afda440ac057a4a7c3789ca740ca109b84c3463e9031a95e0fc1e878487c44ce3d1d4168b21bcd778da9"

[[validator_sets.validators]]
node_id = "0x031c8bc9614e6d2d9c3642a6cfb2c6edbbcee927db4eec4f21c104f84ee886ece0"
stake = 20
cert_pubkey = "0x8e2293ee11161b537de05c7f2f0348e7ddabcbea5a5ffc1c11e5e0432edc0e5a499929173e3f59006ae99a6845405d7d"

[[validator_sets.validators]]
node_id = "0x03f032be493752229481ab235b40d0351e384aeb170d93898f7713b7121460a045"
stake = 20
cert_pubkey = "0x915b8282adc0acd6dfb27203670dbfbcf12579e228d8891b46bc1fba673f6b712ef6b865737d89f99fcc1c44b728e7dd"

[[validator_sets.validators]]
node_id = "0x0265c19d462f24f7ece64ab180b6c7b893b8a8bc4184df8b7d539093e3d5daffee"
stake = 20
cert_pubkey = "0x8d5d5d7477ede7a6e0758379e94798f4db69ee76301749a2e4e39bed7242032c82079ac1204eea80a1f520eaa749ee0d"

[[validator_sets.validators]]
node_id = "0x0316e0861acf92dc4c0e357f73fe07263a87b65513a4b73750ab9194f9a39a6a54"
stake = 20
cert_pubkey = "0xa5861cf9bf42aee127f027efdcd21b5f68b55a28329949baaf057d2810a6d4f977ad58f588833cf3266b192c7417c908"
