---
consensus_ufw_rules:
  validator:
    - port: "{{ monad.validator.consensus.ports.p2p_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: p2p

    - port: "{{ monad.validator.consensus.ports.p2p_port }}"
      proto: udp
      rule: allow
      from: any
      comment: p2p

    - port: "{{ monad.validator.consensus.ports.auth_udp_port }}"
      proto: udp
      rule: allow
      from: any
      comment: auth_udp_port

  fullnode:
    - port: "{{ monad.fullnode.consensus.ports.p2p_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: p2p

    - port: "{{ monad.fullnode.consensus.ports.p2p_port }}"
      proto: udp
      rule: allow
      from: any
      comment: p2p
