---
- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ rpc_home_dir }}"
    directories: "{{ rpc_directories }}"
    log_file_path: "{{ rpc_log_file_path }}"

- name: Include Extract Binaries task
  ansible.builtin.include_tasks: extract_binaries.yml
  vars:
    extracted_dir: "{{ tmp_dir }}/{{ service_identifier }}/usr/local/bin"
    path_mapping:
      - extracted_path: "{{ extracted_dir }}/{{ rpc_binaries.monad_default.default_binary_name }}"
        dest_path: "{{ rpc_bin_dir }}/{{ service_identifier }}"

- name: Copy node configuration and general environment files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  loop:
    - { src: "{{ env }}/node.toml.j2", dest: "{{ rpc_node_config_file_path }}" }
    - { src: "{{ env }}/general.env.j2", dest: "{{ rpc_general_environment_file_path }}" }
  notify:
    - Restart service

- name: Copy systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
