---
- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ cruft_home_dir }}"
    directories: "{{ cruft_directories }}"
    log_file_path: "{{ cruft_log_file_path }}"

- name: Copy cruft script
  ansible.builtin.template:
    src: "clear-old-artifacts.sh.j2"
    dest: "{{ cruft_script_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0755"

- name: Copy cruft systemd service file
  ansible.builtin.template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ service_identifier }}.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service

- name: Copy cruft timer service file
  ansible.builtin.template:
    src: systemd.timer.j2
    dest: "/etc/systemd/system/{{ service_identifier }}.timer"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart timer
