---
# maintains directories and paths
snapshot_sync_home_dir: "/opt/{{ service_identifier }}"

snapshot_sync_bin_dir: "{{ snapshot_sync_home_dir }}/bin"
snapshot_sync_config_dir: "{{ snapshot_sync_home_dir }}/config"
snapshot_sync_data_dir: "{{ snapshot_sync_home_dir }}/data"
snapshot_sync_lib_dir: "{{ snapshot_sync_home_dir }}/lib"
snapshot_sync_socket_dir: "{{ snapshot_sync_home_dir }}/socket"
snapshot_sync_wal_dir: "{{ snapshot_sync_home_dir }}/wal"

snapshot_sync_forkpoint_dir: "{{ snapshot_sync_config_dir }}/forkpoint"

snapshot_sync_directories:
  - "{{ snapshot_sync_data_dir }}"
  - "{{ snapshot_sync_socket_dir }}"
  - "{{ snapshot_sync_wal_dir }}"
  - "{{ snapshot_sync_forkpoint_dir }}"

# config file paths
snapshot_sync_forkpoint_file_path: "{{ snapshot_sync_forkpoint_dir }}/{{ snapshot_sync_forkpoint_file_name }}"
snapshot_sync_validators_config_file_path: "{{ snapshot_sync_config_dir }}/{{ snapshot_sync_validators_config_file_name }}"
