---
- name: Download validator config from URL
  ansible.builtin.get_url:
    url: "{{ monad.validator_config_url }}"
    dest: "{{ sync_node_validators_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service
